CREATE TYPE correo.correspondencia_cab_item AS
   (cab_id_correspondencia integer,
    cab_lugar character varying,
    cab_fecha timestamp without time zone,
    cab_tipo_registro character varying,
    cab_tipo_envio character varying,
    cab_oblea character varying,
    cab_alta_fecha timestamp without time zone,
    cab_alta_usr character varying,
    cab_modi_fecha timestamp without time zone,
    cab_modi_usr character varying,
    cab_baja_fecha timestamp without time zone,
    cab_baja_usr character varying,
    ic_id integer,
    ic_id_correspondencia integer,
    ic_entrada_salida character varying,
    ic_tipo_remitente_destinatario character varying,
    ic_edificio character varying,
    ic_sector character varying,
    ic_usuario character varying,
    ic_empresa_remite character varying,
    ic_sector_remite character varying,
    ic_usuario_remite character varying,
    ic_contenido character varying,
    ic_estado character varying,
    ic_cuil_titular character varying,
    ic_inte integer,
    ic_codigo_farmacia integer,
    ic_otro character varying,
    ic_id_prestador integer,
    ic_cuit_proveedor character varying,
    ic_sucu_proveedor character varying,
    ic_id_punto_venta smallint,
    ic_compro_tipo character varying,
    ic_compro_nro character varying,
    ic_cuit character varying,
    ic_compro_letra character varying,
    ic_compro_sucu integer,
    ic_importe numeric,
    ic_fecha_emision timestamp without time zone,
    ic_fecha_vencimiento timestamp without time zone,
    ic_id_seccional integer,
    ic_alta_fecha timestamp without time zone,
    ic_alta_usr character varying,
    ic_modi_fecha timestamp without time zone,
    ic_modi_usr character varying,
    ic_baja_fecha timestamp without time zone,
    ic_baja_usr character varying,
    ic_alta_sector character varying,
    a_cuil_titular character varying,
    a_inte integer,
    a_id_ospim integer,
    a_id_uoma integer,
    a_id_amtima integer,
    a_apellido character varying,
    a_nombre character varying,
    a_documento_tipo character varying,
    a_sexo character varying,
    a_cuil character varying,
    a_docu_numero character varying,
    f_id_farmacia integer,
    f_farmacia character varying,
    f_cuit character varying,
    f_codigo character varying,
    f_cod_farm character varying,
    f_sucursal character varying,
    prs__id_prestador integer,
    prs__cuit character varying,
    prs__id_tipo_prestador smallint,
    prs__id_seccional integer,
    prs__descripcion character varying,
    e_cuit character varying,
    e_sucursal character varying,
    e_razon_soc character varying,
    e_nombre_fantasia character varying,
    e_id_seccional integer,
    s_id_seccional integer,
    s_descripcion character varying,
    lp_id integer,
    lp_id_paquete integer,
    lp_id_item_correspondencia integer,
    lp_alta_fecha timestamp without time zone,
    lp_alta_usr character varying,
    paq_estado character varying,
    total_registros_v integer);