CREATE TYPE afiliado_opciones AS
   (id_ospim integer,
    id_uoma integer,
    id_amtima integer,
    apellido character varying,
    nombre character varying,
    documento_tipo character varying,
    sexo character varying,
    cuil character varying,
    naci_fecha date,
    civil_esta character varying,
    nacionalidad integer,
    parentesco character varying,
    id_seccional integer,
    anterior_os integer,
    vigen_fecha timestamp without time zone,
    observaciones character varying,
    pres_ssalud_fecha date,
    alta_usr character varying,
    modi_usr character varying,
    discapacitado character varying,
    docu_numero character varying,
    domi_tipo character varying,
    calle character varying,
    piso character varying,
    depto character varying,
    oficina character varying,
    postal_codi character varying,
    barrio character varying,
    telefono character varying,
    tel_laboral character varying,
    celular character varying,
    email character varying,
    observaciones_dom character varying,
    domi_val character varying,
    alta_usr_d character varying,
    modi_usr_d character varying,
    provincia integer,
    localidad integer,
    numero character varying,
    aportante_titular integer,
    baja_f timestamp without time zone,
    baja_u character varying,
    ingre_f date,
    id_motivo_baja integer,
    id_amtima_baja_fecha timestamp without time zone,
    id_ospim_baja_fecha timestamp without time zone,
    id_uoma_baja_fecha timestamp without time zone,
    descripcion character varying,
    cuit character varying,
    razon_soc character varying);