/**
 */
package ar.com.ospim.farmaciaOspim;

/**
 * <a href="WebKeys.java.html"><b><i>View Source</i></b></a>
 *
 * @author SVA
 * 
 */
public class WebKeysFarmaciaOspim implements com.liferay.portal.kernel.util.WebKeys {
	
	public static final String ROL_VER_PORTLET_FARMACIA_OSPIM = "VER_PORTLET_FARMACIA_OSPIM";			
	public static final String ROL_SUBIR_ARCHIVOS = "SUBIR_ARCHIVOS_FARMACIA_OSPIM";		
	public static final String ROL_MEDICAMENTOS_FARMACIA_OSPIM = "MEDICAMENTOS_FARMACIA_OSPIM";
	public static final String ROL_VADEMECUM_FARMACIA_OSPIM = "VADEMECUM_FARMACIA_OSPIM";
	public static final String ROL_FARMACIA_OSPIM = "FARMACIA_OSPIM";

	public static final String BUSQUEDA_REGISTROS_MEDICAMENTOS_OSPIM= "BUSQUEDA_REGISTROS_MEDICAMENTOS_OSPIM";
	public static final String MEDICACION_EN_EDICION= "MEDICACION_EN_EDICION";
	public static final String TIPOS_DE_VENTAS_EN_SESION = "TIPOS_DE_VENTAS_EN_SESION";
	public static final String TOTAL_DE_REGISTROS_BUSQUEDA = "TOTAL_DE_REGISTROS_BUSQUEDA";
	public static final String TOTAL_DE_REGISTROS_BUSQUEDA_FARMACIA = "TOTAL_DE_REGISTROS_BUSQUEDA_FARMACIA";
	public static final String FILTRO_BUSQUEDA_MEDICACION_OFFSET_REG= "FILTRO_BUSQUEDA_MEDICACION_OFFSET_REG";
	public static final String FILTRO_BUSQUEDA_FARMACIA_OSPIM_OFFSET_REG= "FILTRO_BUSQUEDA_FARMACIA_OSPIM_OFFSET_REG";
	public static final String FARMACIA_EN_EDICION= "FARMACIA_EN_EDICION";
	public static final String BUSQUEDA_REGISTROS_FARMACIA_OSPIM= "BUSQUEDA_REGISTROS_FARMACIA_OSPIM";
	public static final String BUSQUEDA_COLEGIO= "BUSQUEDA_COLEGIO";
	
	public static final String PAGINADOR_MEDICACION_FARMACIA_BUSCADOR= "PAGINADOR_MEDICACION_FARMACIA_BUSCADOR";
	public static final String PAGINADOR_FARMACIA_FARMACIA_BUSCADOR= "PAGINADOR_FARMACIA_FARMACIA_BUSCADOR";
	public static final String VADEMECUM_PROCESADO= "VADEMECUM_PROCESADO";
	
	public static final String FILTRO_BUSQUEDA_VADEMECUM_OFFSET_REG= "FILTRO_BUSQUEDA_VADEMECUM_OFFSET_REG";
	public static final String FILTRO_BUSQUEDA_VADEMECUM= "FILTRO_BUSQUEDA_VADEMECUM";
	public static final String TOTAL_DE_REGISTROS_BUSQUEDA_VADEMECUM = "TOTAL_DE_REGISTROS_BUSQUEDA_VADEMECUM";
	public static final String BUSQUEDA_REGISTROS_VADEMECUM= "BUSQUEDA_REGISTROS_VADEMECUM";
	public static final String VADEMECUM_EN_EDICION= "VADEMECUM_EN_EDICION";	
    public static final String LISTADO_PRECIOS_VADEMECUM ="LISTADO_PRECIOS_VADEMECUM"; 	
}
