CREATE TABLE afi_opciones_sss
(
  tipo_exportacion character varying,
  delegacion character varying,
  libro integer,
  tomo integer,
  nro_formulario integer NOT NULL,
  os_elegida integer,
  regimen character varying,
  cuil character varying,
  ape_nom character varying,
  sexo character varying,
  calle character varying,
  numero character varying,
  piso integer,
  departamento character varying,
  localidad character varying,
  telefono_particular character varying,
  telefono_laboral character varying,
  telefono_celular character varying,
  email character varying,
  os_anterior integer,
  cuit character varying,
  unifica_apo character varying,
  fecha_elecc date,
  fecha_certi date,
  cuil_conyuge character varying,
  ape_nom_conyuge character varying,
  fecha_baja date,
  fecha_entrega date,
  numero_lote integer,
  version_sistema character varying,
  de_alta_portal boolean NOT NULL DEFAULT false,
  CONSTRAINT pk_afi_opcionesss PRIMARY KEY (nro_formulario )
)
