#REFERENCIA:
#http://www.tutorialspoint.com/log4j/log4j_patternlayout.htm
#
# Define the root logger with appender file
log4j.rootLogger=DEBUG, FILE, stdout
 
# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

#log4j.rootLogger = DEBUG, FILE
# Define the file appender
log4j.appender.FILE=org.apache.log4j.DailyRollingFileAppender
# Set the name of the file
log4j.appender.FILE.File=${catalina.home}/logs/portalmolineros.log
# Set the immediate flush to true (default)
log4j.appender.FILE.ImmediateFlush=true
# Set the threshold to debug mode
#log4j.appender.FILE.Threshold=debug (mantiene todo log a mismo nivel, no se puede dar niveles diferentes segun Clases)
# Set the append to false, should not overwrite
log4j.appender.FILE.Append=true
# Set the DatePattern // yyyy-MM-dd-a = app.log.2012-11-04-AM
log4j.appender.FILE.DatePattern='.'yyyy-MM-dd-a
# Set the maximum file size before rollover
#log4j.appender.FILE.MaxFileSize=1000KB
# Define the layout for file appender
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.conversionPattern=[%p] %d{ABSOLUTE} [%c:%M(%L)] - %m%n

#log4j.logger.org.aspectj.weaver=WARN
#log4j.logger.org.apache.commons=WARN
log4j.logger.org.apache.axis2=WARN
#log4j.logger.org.apache.axiom=WARN
#log4j.logger.org.apache.xml=WARN

# APPENDER EXLUSIVO SOLO WS 
log4j.appender.WS=org.apache.log4j.DailyRollingFileAppender
log4j.appender.WS.File=${catalina.home}/logs/ws_portalmolineros.log
log4j.appender.WS.ImmediateFlush=true
log4j.appender.WS.Append=true
log4j.appender.WS.DatePattern='.'yyyy-MM-dd-a
log4j.appender.WS.layout=org.apache.log4j.PatternLayout
log4j.appender.WS.layout.conversionPattern=[%p] %d{ABSOLUTE} [%c:%M(%L)] - %m%n

log4j.logger.ar.com.ospim.webservice.PrevencionWSClient=DEBUG, WS
log4j.logger.ar.com.ospim.webservice.prevencion.MembershipServiceStub=DEBUG, WS
log4j.logger.org.apache.axis2=DEBUG, WS
log4j.logger.org.apache.xml=DEBUG, WS
log4j.additivity.ar.com.ospim.webservice.PrevencionWSClient=false
log4j.additivity.ar.com.ospim.webservice.prevencion.MembershipServiceStub=false
log4j.additivity.org.apache.axis2=false
log4j.additivity.org.apache.xml=false






handlers = org.apache.juli.FileHandler, java.util.logging.ConsoleHandler

############################################################
# Handler specific properties.
# Describes specific configuration info for Handlers.
############################################################

org.apache.juli.FileHandler.level = FINE
org.apache.juli.FileHandler.directory = ${catalina.base}/logs
org.apache.juli.FileHandler.prefix = ${classloader.webappName}.

java.util.logging.ConsoleHandler.level = FINE
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter



log4j.appender.HOST-MANAGER = org.apache.log4j.DailyRollingFileAppender
log4j.appender.HOST-MANAGER.File = ${catalina.base}/logs/host-manager
log4j.appender.HOST-MANAGER.Append = true
log4j.appender.HOST-MANAGER.Encoding = UTF-8
log4j.appender.HOST-MANAGER.DatePattern = '.'yyyy-MM-dd'.log'
log4j.appender.HOST-MANAGER.layout = org.apache.log4j.PatternLayout
log4j.appender.HOST-MANAGER.layout.ConversionPattern = %d [%t] %-5p %c- %m%n


