create table detalle_declaracion_jurada(
	fecha_proceso date NOT NULL,
	codigoObraSocial varchar(6),
	periodo timestamp without time zone,
	cuit varchar(11),
	cuil varchar(11),
	remuneracionAfectOS numeric(10,2),
	importeAdicionalOS numeric (6,2),
	zona varchar(2),
	cantGrupoFamiliar varchar(2),
	cantAdherentesGrupoFamiliar varchar(2),
	secObligacion integer,
	condicionCuil varchar(2),
	situacionCuil varchar(2),
	actividad varchar(2),
	modalidad integer,
	codigoSiniestro varchar(2),
	aporteAdicionalOS numeric(6,2),
	versionAplicativo varchar(2) ,
	remuneracionDecreto1273_02 numeric(9,2),
	esposa varchar(1),
	excedenteAporteOS numeric(10,2),
	declaroRetenciones boolean,
	declaro boolean,
	fechaPresentacion timestamp without time zone,
	fechaProceso timestamp without time zone,
	original varchar(1),
	importeBaseContribucionOS numeric(9,2)
)