CREATE TABLE novedades_sss.novedades
(
  id serial NOT NULL,
  id_proceso integer NOT NULL,
  codigo_ooss integer NOT NULL,
  cuit_empleador character varying(11) NOT NULL,
  cuil_titular character varying(11) NOT NULL,
  codigo_parentesco integer NOT NULL,
  cuil character varying(11) NOT NULL,
  documento_tipo character varying(2) NOT NULL,
  documento_numero integer NOT NULL,
  apellido_nombre character varying(30) NOT NULL,
  sexo character varying(1) NOT NULL,
  estado_civil integer,
  fecha_nacimiento integer NOT NULL,
  nacionalidad integer,
  calle character varying(20),
  numero_puerta character varying(5),
  piso character varying(4),
  departamento character varying(4),
  localidad character varying(20),
  codigo_postal character varying(8),
  provincia integer,
  tipo_domicilio integer,
  telefono character varying(20),
  situacion_revista integer,
  incapacidad integer,
  tipo_beneficiario_titular integer NOT NULL,
  fecha_alta_en_ooss integer,
  fecha_cierre_presentacion integer NOT NULL,
  codigo_movimiento character varying(2) NOT NULL,
  detalle_novedad character varying(11),
  alta_fecha timestamp without time zone,
  alta_usr character varying(15),
  modi_fecha timestamp without time zone,
  modi_usr character varying(15),
  baja_fecha timestamp without time zone,
  baja_usr character varying(15),
  CONSTRAINT "NOVEDAD_PRIMARY_KEY" PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);

CREATE TYPE novedades_sss.novedades_detalle AS
   (id integer,
    id_proceso integer,
    codigo_ooss integer,
    cuit_empleador character varying(11),
    cuil_titular character varying(11),
    codigo_parentesco integer,
    parentesco character varying,
    cuil character varying(11),
    documento_tipo character varying(2),
    documento_numero integer,
    apellido_nombre character varying(30),
    sexo character varying(1),
    id_estado_civil_sss integer,
    estado_civil character varying,
    fecha_nacimiento integer,
    nacionalidad integer,
    nacionalidad_detalle character varying,
    calle character varying(20),
    numero_puerta character varying(5),
    piso character varying(4),
    departamento character varying(4),
    localidad character varying(20),
    codigo_postal character varying(8),
    provincia integer,
    tipo_domicilio integer,
    telefono character varying(20),
    id_situacion_revista_sss integer,
    situacion_revista character varying(100),
    incapacidad integer,
    tipo_beneficiario_titular integer,
    fecha_alta_en_ooss integer,
    fecha_cierre_presentacion integer,
    codigo_movimiento character varying(2),
    detalle_novedad character varying(11),
    alta_fecha timestamp without time zone,
    alta_usr character varying(15),
    modi_fecha timestamp without time zone,
    modi_usr character varying(15),
    baja_fecha timestamp without time zone,
    baja_usr character varying(15),
    total_registros_v integer);
    