    #
    # Each portal instance can have its own overriden property file following
    # the convention portal-companyId.properties. To enable this feature, set
    # the "company-id-properties" system property to true.
    #
    # To enable:
    #
    #     java ... company-id-properties=true
    #
    # The read order will now be: portal.properties, then portal-ext.properties,
    # and then portal-liferay.com.properties.
    #
    #include-and-override=portal-${easyconf:companyId}.properties
    #include-and-override=${liferay.home}/portal-${easyconf:companyId}.properties

    #
    # Additional property files can be used by setting the "external-properties"
    # system property.
    #
    # A common use case is to keep legacy property values when upgrading to
    # newer versions of Liferay. To enable:
    #
    #     java ... -Dexternal-properties=portal-legacy-5.1.properties
    #
    # The read order will now be: portal.properties, then portal-ext.properties,
    # and then portal-legacy-5.1.properties.
    #
    #include-and-override=${external-properties}
    #include-and-override=${liferay.home}/${external-properties}

##
## Liferay Home
##

    #
    # PostgreSQL
    #
    jdbc.default.driverClassName=org.postgresql.Driver
    jdbc.default.url=jdbc:postgresql://@IP@:5432/lportal
    jdbc.default.username=postgres
    jdbc.default.password=@PASS@
    #jdbc.default.password=postgres

##
## Groups and Roles
##

    #
    # Input a list of comma delimited system group names that will exist in
    # addition to the standard system groups. When the server starts, the portal
    # checks to ensure all system groups exist. Any missing system group will be
    # created by the portal.
    #
    system.groups=

    #
    # Input a list of comma delimited system role names that will exist in
    # addition to the standard system roles. When the server starts, the portal
    # checks to ensure all system roles exist. Any missing system role will be
    # created by the portal.
    #
    # The standard system roles are: Administrator, Guest, Power User, and User.
    # These roles cannot be removed or renamed.
    #
    system.roles=

    #
    # Set the description of the Administrator system role.
    #
    system.role.Administrator.description=Administrators are super users who can do anything.

    #
    # Set the description of the Guest system role.
    #
    system.role.Guest.description=Unauthenticated users always have this role.

    #
    # Set the description of the Owner system role.
    #
    system.role.Owner.description=This is an implied role with respect to the objects users create.

    #
    # Set the description of the Power User system role.
    #
    system.role.Power.User.description=Power Users have their own public and private pages.

    #
    # Set the description of the User system role.
    #
    system.role.User.description=Authenticated users should be assigned this role.

    #
    # Input a list of comma delimited system community role names that will
    # exist in addition to the standard system community roles. When the server
    # starts, the portal checks to ensure all system community roles exist. Any
    # missing system community role will be created by the portal.
    #
    # The standard system community roles are: Community Administrator,
    # Community Member, and Community  Owner. These roles cannot be removed or
    # renamed.
    #
    system.community.roles=

    #
    # Set the description of the Community Administrator system community role.
    #
    system.community.role.Community.Administrator.description=Community Administrators are super users of their community but cannot make other users into Community Administrators.

    #
    # Set the description of the Community Member system community role.
    #
    system.community.role.Community.Member.description=All users who belong to a community have this role within that community.

    #
    # Set the description of the Community Owner system community role.
    #
    system.community.role.Community.Owner.description=Community Owners are super users of their community and can assign community roles to users.

    #
    # Input a list of comma delimited system organization role names that will
    # exist in addition to the standard system organization roles. When the
    # server starts, the portal checks to ensure all system organization roles
    # exist. Any missing system organization role will be created by the portal.
    #
    # The standard system organization roles are: Organization Administrator,
    # Organization Member, and Organization  Owner. These roles cannot be
    # removed or renamed.
    #
    system.organization.roles=

    #
    # Set the description of the Organization Administrator system organization
    # role.
    #
    system.organization.role.Organization.Administrator.description=Organization Administrators are super users of their organization but cannot make other users into Organization Administrators.

    #
    # Set the description of the Organization Member system organization role.
    #
    system.organization.role.Organization.Member.description=All users who belong to a organization have this role within that organization.

    #
    # Set the description of the Organization Owner system organization role.
    #
    system.organization.role.Organization.Owner.description=Organization Owners are super users of their organization and can assign organization roles to users.

    #
    # Omniadmin users can administer the portal's core functionality: gc,
    # shutdown, etc. Omniadmin users must belong to the default company.
    #
    # Multiple portal instances might be deployed on one application server, and
    # not all of the administrators should have access to this core
    # functionality. Input the ids of users who are omniadmin users.
    #
    # Leave this field blank if users who belong to the right company and have
    # the Administrator role are allowed to administer the portal's core
    # functionality.
    #
    omniadmin.users=

    #
    # Set this to true if all users are required to agree to the terms of use.
    #
    terms.of.use.required=false
    company.security.strangers=false 

    #
    # Specify the group id and the article id of the Journal article that will
    # be displayed as the terms of use. The default text will be used if no
    # Journal article is specified.
    #
    terms.of.use.journal.article.group.id=
    terms.of.use.journal.article.id=

    #
    # Specify subtypes of roles if you want to be able to search for roles
    # using your custom criteria.
    #
    roles.community.subtypes=
    roles.organization.subtypes=
    roles.regular.subtypes=

##
## Organizations
##

    organizations.types=regular-organization,location

    organizations.rootable[regular-organization]=true
    organizations.children.types[regular-organization]=regular-organization,location
    organizations.country.enabled[regular-organization]=false
    organizations.country.required[regular-organization]=false

    organizations.rootable[location]=false
    #organizations.children.types[location]=
    organizations.country.enabled[location]=true
    organizations.country.required[location]=true

    #
    # Input a list of sections that will be included as part of the organization
    # form when adding an organization.
    #
    organizations.form.add.main=details
    organizations.form.add.identification=
    organizations.form.add.miscellaneous=

    #
    # Input a list of sections that will be included as part of the organization
    # form when updating an organization.
    #
    organizations.form.update.main=details,categorization
    organizations.form.update.identification=addresses,phone-numbers,additional-email-addresses,websites,services
    organizations.form.update.miscellaneous=comments,reminder-queries,custom-attributes

    #
    # Set this property to true if you want any administrator that creates an
    # organization to be automatically assigned to that organization.
    #
    organizations.assignment.auto=false

    #
    # Set this property to false if you want any administrator of an
    # organization to be able to assign any user to that organization. By
    # default, he will only be able to assign the users of the organizations
    # and suborganizations that he can manage.
    #
    organizations.assignment.strict=true

    #
    # Set this property to true if you want users to only be members of the
    # organizations to which they are assigned explicitly. By default they will
    # also become implicit members of the ancestors of those organizations.
    # for example if a user belongs to Liferay Spain he will implicitly be a
    # member of the ancestors Liferay Europe and Liferay Global and will be
    # able to access their private pages.
    #
    organizations.membership.strict=false

##
## Languages and Time Zones
##

    #
    # Specify the available locales. Messages corresponding to a specific
    # language are specified in properties files with file names matching that
    # of content/Language_*.properties. These values can also be overridden in
    # properties files with file names matching that of
    # content/Language-ext_*.properties. Use a comma to separate
    # each entry.
    #
    # All locales must use UTF-8 encoding.
    #
    # See the following links specifiy language and country codes:
    #     http://ftp.ics.uci.edu/pub/ietf/http/related/iso639.txt
    #     http://userpage.chemie.fu-berlin.de/diverse/doc/ISO_3166.html
    #
    #locales=ar_SA,eu_ES,ca_AD,ca_ES,zh_CN,zh_TW,cs_CZ,nl_NL,en_US,fi_FI,fr_FR,de_DE,el_GR,hu_HU,it_IT,ja_JP,ko_KR,nb_NO,fa_IR,pl_PL,pt_BR,pt_PT,ru_RU,sk_SK,es_ES,sv_SE,tr_TR,vi_VN
    locales=es_ES

    #
    # Set this to true if unauthenticated users get their preferred language
    # from the Accept-Language header. Set this to false if unauthenticated
    # users get their preferred language from their company.
    #
    locale.default.request=false

    #
    # Specify the available time zones. The specified ids must match those from
    # the class java.util.TimeZone.
    #
    time.zones=\
    	America/Buenos_Aires,\
        Pacific/Midway,\
        Pacific/Honolulu,\
        America/Anchorage,\
        America/Los_Angeles,\
        America/Denver,\
        America/Chicago,\
        America/New_York,\
        America/Puerto_Rico,\
        America/St_Johns,\
        America/Sao_Paulo,\
        America/Noronha,\
        Atlantic/Azores,\
        UTC,\
        Europe/Lisbon,\
        Europe/Paris,\
        Europe/Istanbul,\
        Asia/Jerusalem,\
        Asia/Baghdad,\
        Asia/Tehran,\
        Asia/Dubai,\
        Asia/Kabul,\
        Asia/Karachi,\
        Asia/Calcutta,\
        Asia/Katmandu,\
        Asia/Dhaka,\
        Asia/Rangoon,\
        Asia/Saigon,\
        Asia/Shanghai,\
        Asia/Tokyo,\
        Asia/Seoul,\
        Australia/Darwin,\
        Australia/Sydney,\
        Pacific/Guadalcanal,\
        Pacific/Auckland,\
        Pacific/Enderbury,\
        Pacific/Kiritimati

##
## Look and Feel
##

    #
    # Set this to false if the system does not use allow users to modify the
    # look and feel.
    #
    look.and.feel.modifiable=false

    #
    # Set the default layout template id.
    #
    default.layout.template.id=2_columns_ii

    #
    # Set the default theme id for regular themes.
    #
    default.regular.theme.id=classic

    #
    # Set the default color scheme id for regular themes.
    #
    default.regular.color.scheme.id=01

    #
    # Set the default theme id for wap themes.
    #
    default.wap.theme.id=mobile

    #
    # Set the default color scheme id for wap themes.
    #
    default.wap.color.scheme.id=01

    #
    # Set this to true if you want a change in the theme selection of the public
    # or private group to automatically be applied to the other (i.e. if public
    # and private group themes should always be the same).
    #
    theme.sync.on.group=false

##
## Request
##

    #
    # Portlets that have been configured to use private request attributes in
    # liferay-portlet.xml may still want to share some request attributes. This
    # property allows you to configure which request attributes will be shared.
    # Set a comma delimited list of attribute names that will be shared when the
    # attribute name starts with one of the specified attribute names. For
    # example, if you set the value to "hello_,world_", then all attribute names
    # that start with "hello_" or "world_" will be shared.
    #
    request.shared.attributes=LIFERAY_SHARED_

##
## Session
##

    #
    # Specify the number of minutes before a session expires. This value is
    # always overridden by the value set in web.xml.
    #
    session.timeout=120

    #
    # Specify the number of minutes before a warning is sent to the user
    # informing the user of the session expiration. Specify 0 to disable any
    # warnings.
    #
    session.timeout.warning=5

    #
    # Set the auto-extend mode to true to avoid having to ask the user whether
    # to extend the session or not. Instead it will be automatically extended.
    # The purpose of this mode is to keep the session open as long as the user
    # browser is open and with a portal page loaded. It is recommended to use
    # this setting along with a smaller "session.timeout", such as 5 minutes for
    # better performance.
    #
    session.timeout.auto.extend=false

    #
    # Set this to true if the user is redirected to the default page when the
    # session expires.
    #
    session.timeout.redirect.on.expire=false

    #
    # Portlets that have been configured to use private session attributes in
    # liferay-portlet.xml may still want to share some session attributes. This
    # property allows you to configure which session attributes will be shared.
    # Set a comma delimited list of attribute names that will be shared when the
    # attribute name starts with one of the specified attribute names. For
    # example, if you set the value to "hello_,world_", then all attribute names
    # that start with "hello_" or "world_" will be shared.
    #
    # Note that this property is used to specify the sharing of session
    # attributes from the portal to the portlet. This is not used to specify
    # session sharing between portlet WARs or from the portlet to the portal.
    #
    session.shared.attributes=org.apache.struts.action.LOCALE,COMPANY_,USER_,LIFERAY_SHARED_

    #
    # Set this to false to disable all persistent cookie. Features like
    # automatically logging in will not work.
    #
    session.enable.persistent.cookies=true

    #
    # Set this to true to enable sessions when cookies are disabled. See
    # LEP-4787. This behavior is configurable because enabling it can break
    # certain setups.
    #
    session.enable.url.with.session.id=true

    #
    # The login process sets several cookies if persistent cookies are enabled.
    # Set this property to set the domain of those cookies.
    #
    #session.cookie.domain=

    #
    # Set this to true to invalidate the session when a user logs into the
    # portal. This helps prevents phishing. Set this to false if you need the
    # guest user and the authenticated user to have the same session.
    #
    session.enable.phishing.protection=true

    #
    # Set this to true to test whether users have cookie support before allowing
    # them to sign in. This test will always fail if "tck.url" is set to true
    # because that property disables session cookies.
    #
    session.test.cookie.support=true

    #
    # Set this to true to disable sessions. Doing this will use cookies to
    # remember the user across requests. This is useful if you want to scale
    # very large sites where the user may be sent to a different server for each
    # request. The drawback to this approach is that you must not rely on the
    # API for sessions provided by the servlet and portlet specs.
    #
    # This feature is only available for Tomcat and requires that you set
    # Tomcat's Manager class to
    # "com.liferay.support.tomcat.session.SessionLessManagerBase".
    #
    session.disabled=false

    #
    # Input a list of comma delimited class names that extend
    # com.liferay.portal.struts.SessionAction. These classes will run at the
    # specified event.
    #

    #
    # Servlet session create event
    #
    servlet.session.create.events=com.liferay.portal.events.SessionCreateAction

    #
    # Servlet session destroy event
    #
    servlet.session.destroy.events=com.liferay.portal.events.SessionDestroyAction

    #
    # Set this to true to track user clicks in memory for the duration of a
    # user's session. Setting this to true allows you to view all live sessions
    # in the Admin portlet.
    #
    session.tracker.memory.enabled=true

    #
    # Set this to true to track user clicks in the database after a user's
    # session is invalidated. Setting this to true allows you to generate usage
    # reports from the database. Use this cautiously because this will store a
    # lot of usage data.
    #
    session.tracker.persistence.enabled=false

    #
    # Set this to true to convert the tracked paths to friendly URLs.
    #
    #session.tracker.friendly.paths.enabled=false

    #
    # Enter a list of comma delimited paths that should not be tracked.
    #
    session.tracker.ignore.paths=\
        /portal/render_portlet,\
        \
        /document_library/get_file    
        
    #set the default Start page for a standard user upon login.
	default.landing.page.path=/web/guest/login

    #cambia el directorio lucene
    @LUCENE_DIR@
    wiki.front.page.name=Wiki Portal Molineros
    
    users.form.add.category.molineros=crmUser
    
    #tamaño max de los archivos a subir
    dl.file.max.size=5120000
    
    #dl.hook.file.system.root.dir=C:/Users/30DeJunioSERVIDOR/document_library
    dl.hook.file.system.root.dir=/etc/data/document_library
	#dl.hook.file.system.root.dir=/home/sergio/data/document_library
    
     
    #dl.file.extensions 	.bmp,.css,.doc,.docx,.dot,.gif,.gz, .htm,.html,.jpg,.js,.lar,.odb,.odf,.odg,.odp,...  
        ## WEB SERVICES
	#main.servlet.hosts.allowed=
	#main.servlet.https.required=false
	
	#axis.servlet.hosts.allowed=127.0.0.1,SERVER_IP
	axis.servlet.hosts.allowed=
	#axis.servlet.https.required=false
	axis.servlet.https.required=true
		
	tunnel.servlet.hosts.allowed=
	#tunnel.servlet.https.required=false
	tunnel.servlet.https.required=true	
    
    webdav.servlet.hosts.allowed=SERVER_IP,12.1.1.103,127.0.0.1
    webdav.servlet.https.required=false
    
