CREATE TABLE padron27092010 (
    nro_afil character varying(50),
    seccional character varying(50),
    prestador character varying(100),
    cuil character varying(20),
    pare character varying(50),
    parentesco character varying(200),
    apellido character varying(100),
    nombre character varying(100),
    tdoc character varying(50),
    documento character varying(50),
    f_nac character varying(50),
    edad character varying(50),
    sexo character varying(50),
    est_civil character varying(50),
    nacion character varying(50),
    provincia character varying(50),
    localidad character varying(50),
    cp character varying(50),
    direccion character varying(250),
    altura character varying(50),
    piso character varying(10),
    dpto character varying(10),
    telefono character varying(50),
    categoria character varying(50),
    plan character varying(100),
    ingreso character varying(50),
    baja character varying(50),
    cuit character varying(20),
    sucu character varying(10),
    empleador character varying(100),
    ing_lab character varying(50),
    antiguedad character varying(50),
    ramo character varying(100),
    unifica character varying(50),
    observa character varying(100),
    secc character varying(10),
    ospim character varying(50),
    uoma character varying(50),
    amtima character varying(50),
    nombreb character varying(100),
    cuip character varying(20),
    revisa character varying(100),
    disca character varying(10),
    osanterior character varying(100),
    sssalud character varying(20)
);


ALTER TABLE public.padron27092010 OWNER TO postgres;

--
