package ar.com.ospim.prestadores;

public class WebKeysPrestadores {

    public static final String BUSQUEDA_CARTILLA_CONVENIO_FILTRO = "BUSQUEDA_CARTILLA_CONVENIO_FILTRO";
    public static final String BUSQUEDA_CARTILLA_CONVENIO_RESULTS = "BUSQUEDA_CARTILLA_CONVENIO_RESULTS";
    public static final String PROVINCIAS_EN_SESSION = "PROVINCIAS_EN_SESSION";
    public static final String LOCALIDADES_EN_SESSION = "LOCALIDADES_EN_SESSION";
    public static final String BUSQUEDA_CONVENIOS_PRESTAC_RESULTS = "BUSQUEDA_CONVENIOS_PRESTAC_RESULTS";
    public static final String BUSQUEDA_CONVENIOS_PRESTAC_FILTRO = "BUSQUEDA_CONVENIOS_PRESTAC_FILTRO";
    public static final String CONVENIO_PREST_EN_EDICION = "CONVENIO_PREST_EN_EDICION";
    public static final String CONVENIO_PREST_DETALLE_EN_EDICION = "CONVENIO_PREST_DETALLE_EN_EDICION";
    public static final String CONVENIO_PREST_DETALLES_EN_SESSION = "CONVENIO_PREST_DETALLES_EN_SESSION";
    public static final String CONVENIO_PREST_DETALLES_EN_SESSION_DESGLOSE = "CONVENIO_PREST_DETALLES_EN_SESSION_DESGLOSE";
    public static final String PLANES_EN_SESSION  = "PLANES_EN_SESSION";
    public static final String LISTAS_DE_ESPECIALIDAD_PRESTADOR_EN_SESSION = "LISTAS_DE_ESPECIALIDAD_PRESTADOR_EN_SESSION";
    public static final String PLANES_PRESTADOR_EN_SESSION = "PLANES_PRESTADOR_EN_SESSION";
    public static final String TIPOS_PAGO_CONVENIOS_PREST_EN_SESSION = "TIPOS_PAGO_CONVENIOS_PREST_EN_SESSION";
    public static final String TIPOS_NOMENCLADORES_EN_SESSION = "TIPOS_NOMENCLADORES_EN_SESSION";
}
