CREATE TABLE correo.cabecera_item_correspondencia_historico
(
  id_histo integer NOT NULL DEFAULT nextval('correo.entrada_item_correspondencia_historico_id_histo_seq1'::regclass),
  id_correspondencia_c integer,
  lugar_recep_emision character varying,
  fecha timestamp without time zone,
  tipo_registro character varying,
  tipo_envio character varying,
  oblea	character varying,
  alta_fecha_c timestamp without time zone,
  alta_usr_c character varying,
  modi_fecha_c timestamp without time zone,
  modi_usr_c character varying,
  baja_fecha_c timestamp without time zone,
  baja_usr_c character varying,
  id_i integer,
  id_correspondencia_i integer NOT NULL,
  entrada_salida character varying,
  tipo_remitente_destinatario character varying,
  edificio character varying,
  sector character varying,
  usuario character varying,
  contenido character varying,
  estado character varying,
  cuil_titular character varying,
  inte integer,
  codigo_farmacia integer,
  descripcion_otro character varying,
  id_prestador integer,
  cuit_proveedor character varying,
  sucu_proveedor character varying,
  id_punto_venta smallint,
  compro_tipo character varying,
  compro_nro character varying,
  cuit character varying,
  compro_letra character varying,
  compro_sucu integer,
  importe numeric,
  fecha_emision timestamp without time zone,
  fecha_vencimiento timestamp without time zone,
  id_seccional integer,
  alta_fecha_i timestamp without time zone,
  alta_usr_i character varying,
  modi_fecha_i timestamp without time zone,
  modi_usr_i character varying,
  baja_fecha_i timestamp without time zone,
  baja_usr_i character varying
)
WITH (
  OIDS=FALSE
);
