corre_ws_client = false
corre_java_agendado = false
#url p/pruebas sin seguridad
#prevencion_url_service = http://200.41.127.78/Membership/MembershipService.svc
#url p/pruebas con seguridad
#prevencion_url_service = https://integration-pre-ws.gruposancorseguros.com/PrevencionSaludValidatorPublic/Membership/MembershipService.svc
prevencion_url_service = https://integration-pre-ws.gruposancorseguros.com/PrevencionSaludValidatorPublicCli/Membership/MembershipService.svc 
#prevencion PRODUCCION
#prevencion_url_service=https://integration-pro-ws.gruposancorseguros.com/PrevencionSaludValidatorPublic/Membership/MembershipService.svc 
hoteles_transferencia_url_service=http://200.125.119.204:8080/transferenciahoteles.webservice/services/SincronizarHoteles