package ar.com.ospim.comprobantesPortalProveedores.services;

public class WebKeysComprobantes implements
		com.liferay.portal.kernel.util.WebKeys {
	
	
	public static final String COMPROBANTES_FILTRO = "COMPROBANTES_FILTRO";
	public static final String COMPROBANTES_RESULT = "COMPROBANTES_RESULT";
	public static final String COMPROBANTES_RESULT_PROCESADOS = "COMPROBANTES_RESULT_PROCESADOS";
	public static final String COMPROBANTES_RESULT_ERRONEOS = "COMPROBANTES_RESULT_ERRONEOS";
	
	public static final String COMPROBANTES_PROVEDORES_OFFSET_REG="COMPROBANTES_PROVEDORES_OFFSET_REG";
	public static final String COMPROBANTES_PROVEEDORES_TOTAL_REGISTROS="COMPROBANTES_PROVEEDORES_TOTAL_REGISTROS"; 
	
	public static final String COMPROBANTE_IMAGEN_VIEW = "COMPROBANTE_IMAGEN_VIEW";
	
	public static final String COMPROBANTE_IMAGEN_FOLDER = "COMPROBANTE_IMAGEN_FOLDER";
	public static final String COMPROBANTE_IMAGEN_NAME = "COMPROBANTE_IMAGEN_NAME";
	
	public static final String COMPROBANTE_PROVEEDOR_EN_EDICION = "COMPROBANTE_PROVEEDOR_EN_EDICION";
	
	public static final String COMPROBANTE_SECTOR_EN_EDICION = "COMPROBANTE_SECTOR_EN_EDICION";
	
	public static final String ROL_ADMINISTRACION = "COMPROBANTES_ROL_ADMINISTRACION";
	
	public static final String ROL_INTEGRACION = "ABM_Integracion";
	public static final String ROL_ACOMPANANTE = "ABM_Acompanante_terapeutico";
	public static final String ROL_HOSPITALES = "ABM_Hospitales";
	public static final String ROL_FARMACIA = "ABM_Comprobantes_Farmacia";
	public static final String ROL_PROVEEDORES = "ABM_Proveedores";
	public static final String ROL_GERENCIADORAS="ABM_Gerenciadoras";
	
	public static final String COMPROBANTES_FILTRO_INTEGRACION = "COMPROBANTES_FILTRO_INTEGRACION";
	public static final String COMPROBANTES_RESULT_INTEGRACION = "COMPROBANTES_RESULT_INTEGRACION";
	
	public static final String COMPROBANTE_INTEGRACION_EN_EDICION = "COMPROBANTE_INTEGRACION_EN_EDICION";

	public static final String COMPROBANTES_FILTRO_ACOMPANANTES = "COMPROBANTES_FILTRO_ACOMPANANTES";
	public static final String COMPROBANTES_RESULT_ACOMPANANTES = "COMPROBANTES_RESULT_ACOMPANANTES";
	public static final String COMPROBANTE_ACOMPANANTE_EN_EDICION = "COMPROBANTE_ACOMPANANTE_EN_EDICION";
	public static final String COMPROBANTES_FILTRO_HOSPITALES = "COMPROBANTES_FILTRO_HOSPITALES";
	public static final String COMPROBANTES_RESULT_HOSPITALES = "COMPROBANTES_RESULT_HOSPITALES";
	public static final String COMPROBANTE_HOSPITALES_EN_EDICION = "COMPROBANTE_HOSPITALES_EN_EDICION";
	
	public static final String COMPROBANTES_FILTRO_FARMACIA = "COMPROBANTES_FILTRO_FARMACIA";
	public static final String COMPROBANTES_RESULT_FARMACIA = "COMPROBANTES_RESULT_FARMACIA";
	public static final String COMPROBANTE_FARMACIA_EN_EDICION = "COMPROBANTE_FARMACIA_EN_EDICION";
	
	public static final String COMPROBANTES_FILTRO_PROVEEDORES = "COMPROBANTES_FILTRO_PROVEEDORES";
	public static final String COMPROBANTES_RESULT_PROVEEDORES = "COMPROBANTES_RESULT_PROVEEDORES";
	public static final String COMPROBANTE_PROVEEDORES_EN_EDICION = "COMPROBANTE_PROVEEDOFES_EN_EDICION";
	
	public static final String COMPROBANTES_FILTRO_GERENCIADORAS = "COMPROBANTES_FILTRO_GERENCIADORAS";
	public static final String COMPROBANTES_RESULT_GERENCIADORAS = "COMPROBANTES_RESULT_GERENCIADORAS";
	public static final String COMPROBANTE_GERENCIADORA_EN_EDICION = "COMPROBANTE_GERENCIADORA_EN_EDICION";
}

	
	